vim.wo.number = true            -- Make line numbers defualt (default: false)
vim.o.relativenumber = true     -- Set relative line numbers (default: false)
vim.o.clipboard = 'unnamedplus' -- Sync clipboard between OS and Neovim
vim.o.wrap = false              -- Display lines as one long line (default: true)
vim.o.linebreak = true          -- Companion to wrap, dont split words (defualt: false)
vim.o.mouse = 'a'               -- Enable mouse mode
vim.o.autoindent = true         -- Copy indent from current line when starting new one (default: true)
vim.o.ignorecase = true         -- Case insensitive searching unless \C or capital in search
vim.o.smartcase = true          -- Smart case
vim.o.shiftwidth = 4            -- Number of spaces inserted for each indentation
vim.o.tabstop = 4               -- Insert 4 spaces for a tab
vim.o.softtabstop = 4           -- Number of spaces that a tab counts for while
vim.o.hlsearch = true           -- Set highlight on search
vim.o.undofile = true           -- Save undo history
vim.o.signcolumn = 'yes'        -- Keep signcolumn on by default
vim.o.timeoutlen = 300          -- time to wait for a mapped sequence to complete (in milliseconds)
vim.o.cursorline = true         -- highlight the current line
vim.o.splitbelow = true         -- force all horizontal splits to go below current window
vim.o.splitright = true         -- force all vertical splits to go to the right of current window
vim.o.smartindent = true        -- make indenting smarter again
vim.o.showmode = true           -- See things like -- INSERT --
vim.o.showtabline = 0           -- Show tabs
vim.o.pumheight = 10            -- pop up menu height
vim.o.conceallevel = 0          -- so that `` is visible in markdown files
vim.o.fileencoding = 'utf-8'    -- the encoding written to a file
vim.o.encoding = 'utf-8'
vim.o.cmdheight = 1             -- more space in the neovim command line for displaying messages
vim.opt.iskeyword:append '-'    -- hyphenated words recognized by searches
vim.o.updatetime = 250          -- Decrease update time (from neovim kickstart config)
vim.o.timeoutlen = 300          -- Decrease mapped sequence wait time (from neovim kickstart config)
vim.o.cursorline = true         -- Show which line your cursor is on
vim.o.scrolloff = 10            -- Minimal number of screen lines to keep above and below the cursor.
vim.o.confirm = true            -- if performing an operation that would fail due to unsaved changes in the buffer (like `:q`), instead raise a dialog asking if you wish to save the current file(s)
